name_of_the_user = input("Enter your name")
length_of_the_name = len(name_of_the_user)
print(type(name_of_the_user))
print(type(length_of_the_name))
print("Number of letters in your name: " + str(length_of_the_name))